# Generated by Django 5.0.4 on 2024-06-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navagos_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='chosen_answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='navagos_main.answer'),
        ),
    ]
