# Generated by Django 5.0.4 on 2024-04-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navagos_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='QuestionAnswers',
            new_name='QuestionAnswer',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.RenameModel(
            old_name='TestQuestions',
            new_name='TestQuestion',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
