# Generated by Django 5.0.4 on 2024-06-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navagos_main', '0003_alter_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
